learningSignals/DS/urls.py
from django.urls import path
from . import views
from .views import UserRegister

app_name='DS'

urlpatterns =[
    path('', views.home, name='home'),
    path('register', UserRegister.as_view(), name='user-register'),
]

learningSignals/learningSignals/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('DS/', include('DS.urls'))
]

learningSignals/DS/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# A user profile will be created whenever a user gets register using  the post_save signal.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)
    address = models.CharField(max_length=100, blank=True)
    mobile_number = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.user.username

'''
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = UserProfile.objects.create(user=instance)

post_save.connect(receiver=create_user_profile, sender=User)
'''

learningSignals/DS/views.py
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy

from django.core.signals import request_finished
from django.dispatch import receiver

def home(request):
    return HttpResponse('You are at the homepage')

'''
def my_first_callback(sender, **kwargs):
    print('Request finished')

request_finished.connect(my_first_callback)
'''

@receiver(request_finished)
def my_second_callback(sender, **kwargs):
    print("Request finished with no errors.")

class UserRegister(CreateView):
    form_class = UserCreationForm
    template_name = 'DS/user_register.html'
    success_url = reverse_lazy('DS:home')

learningSignals/DS/templates/DS/userRegister.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'DS:userRegister' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
</body>
</html>

learningSignals/DS/templates/DS/user_register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'DS:user-register' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
</body>
</html>